方塊化3D物件
---

這段程式碼的主要用途如下：

 
1. **簡化幾何物件並重建網格結構** 

此腳本適用於 HFSS/Q3D/Maxerll/Icepak，透過讀取選取的幾何物件，提取其材質和顏色，並分析其包圍盒 (bounding box)。程式將這些物件劃分成規則的網格，藉由分析三維空間中的連續區域，合併相鄰區域以簡化模型結構，最後重新建立更簡單的幾何方塊 (box)。
 
2. **區域合併與優化處理** 

程式碼利用 `continuous_count()` 和 `defaultdict` 來整理連續的區域，避免逐點生成方塊，而是合併相鄰的部分，減少幾何數量，從而降低計算成本。同時，忽略 `vacuum` 材質的物件，確保不影響模擬精度。
 
3. **顏色與材質的保留與應用** 

在生成新的簡化幾何物件時，會保留原始物件的顏色與材質，確保視覺呈現的一致性。`changecolor()` 函式負責將新生成的方塊調整為與原物件相同的顏色，確保後續分析或視覺化時仍能識別不同材質的區塊。

![2025-03-12_13-40-17](/assets/2025-03-12_13-40-17.png)

```python
size = 1

from math import floor, ceil
from collections import defaultdict
import itertools
import time

t0 = time.time()
oDesktop.ClearMessages("", "", 2)
oProject = oDesktop.GetActiveProject()
oDesign = oProject.GetActiveDesign()
oEditor = oDesign.SetActiveEditor("3D Modeler")

unit = oEditor.GetModelUnits()
n = 0

def float_range(xmin, xmax, step):
    result = []
    x = xmin
    while x <= xmax:
        result.append(x)
        x += step
        
    return result

def changecolor(obj_list, code):
    code = int(code)
    R= code % 256
    G = ((code - R) % (256**2)) / 256
    B = (code - R - 256*G) / 256**2
    
    oEditor.ChangeProperty(
        [
            "NAME:AllTabs",
            [
                "NAME:Geometry3DAttributeTab",
                [
                    "NAME:PropServers", 
                ] + obj_list,
                [
                    "NAME:ChangedProps",
                    [
                        "NAME:Color",
                        "R:="			, int(R),
                        "G:="			, int(G),
                        "B:="			, int(B)
                    ]
                ]
            ]
        ])

def continuous_count(x):
    result = []
    i0, loc0 = x[0]
    count = 1
    for i, loc in x[1:]:
        if i == i0:
            count += 1
        else:
            result.append((i0, loc0, count))
            i0, loc0 = i, loc
            count = 1
    result.append((i0, loc0, count))
    return result
    
def createcell(x, y, z, Nx, Ny, material):
    global n
    newname = oEditor.CreateBox(
        [
            "NAME:BoxParameters",
            "XPosition:="		, str(x-size/2) + unit,
            "YPosition:="		, str(y-size/2) + unit,
            "ZPosition:="		, str(z-size/2) + unit,
            "XSize:="		, str(size*Nx) + unit,
            "YSize:="		, str(size*Ny) + unit,
            "ZSize:="		, str(size) + unit
        ], 
        [
            "NAME:Attributes",
            "Name:="		, 'box{}'.format(n),
            "Flags:="		, "",
            "Color:="		, "(143 175 143)",
            "Transparency:="	, 0.9,
            "PartCoordinateSystem:=", "Global",
            "UDMId:="		, "",
            "MaterialValue:="	, material,
            "SurfaceMaterialValue:=", "\"\"",
            "SolveInside:="		, True,
            "ShellElement:="	, False,
            "ShellElementThickness:=", "0mm",
            "IsMaterialEditable:="	, True,
            "UseMaterialAppearance:=", False,
            "IsLightweight:="	, True
        ])
    n += 1    
    return newname


color = {}
material = {}
vertex_positions = []

total = oEditor.GetSelections()
if len(total) == 0:
    MessageBox.Show("Please select objects to simplify!", 'Message Window')
    
for obj in total:
    try:
        material[obj] = oEditor.GetPropertyValue('Geometry3DAttributeTab', obj, 'Material')
        color[obj] = oEditor.GetPropertyValue('Geometry3DAttributeTab', obj, 'Color')
        
        bounding_box = [float(i) for i in oEditor.GetObjectBoundingBox(obj)]
        vertex_positions += [bounding_box[0:3], bounding_box[3:6]]
    except:
        AddWarningMessage('{} is ignored!'.format(obj))


#%%
vs = list(zip(*vertex_positions))
size_range = list(map(floor, map(min, vs))) + list(map(ceil, map(max, vs)))

xmin, ymin, zmin, xmax, ymax, zmax = map(int, size_range)

xrange = float_range(xmin, xmax, size)
yrange = float_range(ymin, ymax, size)
zrange = float_range(zmin, zmax, size)

#%%
data = defaultdict(list)

for k , j in itertools.product(zrange, yrange):
    queue = []
    for i in xrange:
        o = oEditor.GetBodyNamesByPosition(["NAME:Parameters", "XPosition:=", str(i)+unit,"YPosition:=", str(j)+unit, "ZPosition:=", str(k)+unit])
        if o:
            queue.append((o[0],i))
        else:
            queue.append(('dummy',i))
    
    for obj, loc, xlen in continuous_count(queue):
        if obj in total:
            data[obj] += [(loc, j, k, xlen)]
    
models = defaultdict(list)

for obj in data:
    if obj == '':
        continue
    i0, j0, k0, xlen0 = data[obj][0]
    ylen = 1

    for u in data[obj][1:]:
        
        i, j, k, xlen = u
        if (i, k, xlen) == (i0, k0, xlen0):
            ylen += 1
        else:
            models[obj] += [(i0, j0, k0, xlen0, ylen)]
            
            i0, j0, k0, xlen0 = i, j, k, xlen
            ylen = 1
    models[obj] += [(i0, j0, k0, xlen0, ylen)]

for obj in models:
    cubes = []
    m = material[obj]
    
    if 'vacuum' in m:
        continue
        
    for x, y, z, Nx, Ny in models[obj]:
        name = createcell(x, y, z, Nx, Ny, m)
        cubes.append(name)
        
    changecolor(cubes, color[obj])
```